### ISSUE TITLE
Seit kurzem ohne Funktion

### ISSUE THREAD

**Issue by DNC74** [lrswss/akal2ical#1]
Hallo Lars,
vorab vielen lieben Dank für Dein schickes Skript.

Leider liefert es seit (vermutlich 2-3 Tagen) keine Daten mehr.

`~/akal2ical $ ./akal2ical.pl --strasse 'ADENAUERRING' --nummer '36' --test`
`Nach dem Straßennamen 'ADENAUERRING' beim AfA Karlsruhe suchen...`
`Keinen passenden Straßennamen zur Anfrage 'ADENAUERRING' gefunden.`

Es wäre echt super von Dir, wenn Du Dir das anschauen könntest.

Besten Dank und viele Grüße
DNC

**Comment by DNC74** [comment]
Hallo Lars,

ich habe einmal selbst versucht, mich mit dem Code näher zu beschäftigen und ich denke, ich habe das Problem gefunden:
Die URL `https://web6.karlsruhe.de/service/abfall/akal/akal.php?von=A&bis=Z` gibt es nicht mehr.
Ich bin daher testweise hergegangen, und habe die Zeile 147 `my $street = &query_streets($street);  # Rückgabe bei gültigem Straßenamen` auskommentiert. Und siehe da, es werden wieder Werte geliefert.

Grüße
DNC

**Comment by NemesisRE** [comment]
Also ich kann das so nicht bestätigen sowohl script also auch die von dir genannte URL funktionieren.

**Comment by DNC74** [comment]
Dann präzisiere ich meine obige Aussage nochmal:
Zeile 147 versucht alle Straßennamen von `https://web6.karlsruhe.de/service/abfall/akal/akal.php?von=A&bis=Z` abzurufen. 
Ja, die URL existiert, die Parametrisierung `?von=A&bis=Z` gibt jedoch keine Straßennamen mehr zurück, und damit kommt es zu dem oben genannten Verhalten.

Ich vermute, der Sinn hinter Zeile 147 ist, dass damit die per Parameter angegebenen Straßennamen validiert bzw. alle verfügbaren Straßennamen abgerufen werden sollen. Kommt dort kein Ergebnis, arbeitet das Script jedoch nicht weiter, da die `sub query_streets()`' mit nem exit aussteigt.

Durch das Auskommentieren dieser Zeile findet diese Prüfung nicht statt, und das Script extrahiert wie gewohnt die Werte und füllt das ICAL. Das Auskommentieren war auch nur ein Workaround für mich oder auch andere, die das gleiche Problem haben. Schöner wäre es natürlich, wenn Lars das grundsätzlich beheben könnte.

**Comment by NemesisRE** [comment]
Ich wollte meinen Kommentar gerade editieren weil ich das Problem jetzt gesehen habe und das verhalten beobachten konnte. Aber deine Präzisere aussage ist trotzdem gut :)

**Comment by DNC74** [comment]
ich habe mal den Seitenquelltext genauer abgesehen. Es sieht so aus, als ob alle Straßennamen mittlerweile in einer Variablen geführt werden:
`var strassenliste = ['ABRAHAM-LINCOLN-ALLEE','ACHERSTRAßE', ... ,'ZYPRESSENWEG',]`
Vielleicht lässt sich das ja auch per Perl verarbeiten? Dann wäre die Abfrage auf `?von=A&bis=Z` ja hinfällig bzw. dadurch zu ersetzen.

**Comment by lrswss** [comment]
Sorry, bin leider erst heute dazu gekommen, dass Skript an die neue Auto-Complete-Funktion auf der AfA-Seite anzupassen.
